language: python
python:
  - "2.7"
install:
  - make deps
services:
  - docker
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
        provider: heroku
        app: peaceful-lake-98705
        api_key: ${HEROKU_API_KEY}
